language: python
sudo: false
cache:
  - pip
services:
  - memcached
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - DJANGO="Django<1.7,>=1.6"
    - DJANGO="Django<1.8,>=1.7"
    - DJANGO="Django<1.9,>=1.8"
    - DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO="Django<1.7,>=1.6"
    - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
    - python: "pypy"
    - python: "pypy3"
install:
  - pip install --upgrade pip
  - pip install -e .
  - pip install -r requirements_dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install python-memcached; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install python3-memcached; fi
  - pip install $DJANGO
  - pip install coveralls
  - sh -e /etc/init.d/xvfb start
script:
  - isort --check-only --recursive --diff .
  - flake8 --jobs=2 .
  - pep257 django_select2
  - coverage run --source=django_select2 runtests.py
after_success:
  - coveralls
