language: python
sudo: false
dist: trusty
cache:
- apt
- pip
services:
- redis
addons:
  chrome: stable
  apt:
    packages:
    - python3-enchant
    - python-enchant
    - graphviz
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  matrix:
  - DJANGO=18
  - DJANGO=110
  - DJANGO=111
  - DJANGO=master
  - TOXENV=qa
  - TOXENV=docs
matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO=master
  exclude:
  - env: DJANGO=master
    python: "2.7"
  - env: TOXENV=qa
    python: "2.7"
  - env: TOXENV=qa
    python: "3.5"
  - env: TOXENV=docs
    python: "2.7"
  - env: TOXENV=docs
    python: "3.5"
install:
- pip install --upgrade pip tox
- pip install -U coveralls
before_script:
- mkdir bin
- export CHROME_DRIVER_VERSION=`curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
- curl -O https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d bin
- PATH=$PATH:$PWD/bin
- nvm install --lts
- npm install -g standard
- |
  if [[ -z $TOXENV ]]; then
    export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
- echo $TOXENV
script:
- tox -e $TOXENV
- standard
after_success:
- coveralls
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: fEP9K7y0ZF9fRvQEUN4kgPXQEZvi3Cx3ikUebG2UM/2uhcaUQm0+KpgZ2S+lvOTYcBnNgzPzFsVIZMcVcTxwIKuQDEMq9y2eop2hnisb9KXsIm9qPYSzOnRm74VuiOt4hNOZMe0qVBK2cO3vC9NDXuzdI8A0JynJhthfl4t+kFM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: applegrew/django-select2
