language: python
sudo: true
dist: xenial
cache:
- apt
- pip
services:
- redis
addons:
  apt:
    packages:
    - chromium-chromedriver
    - python3-enchant
    - python-enchant
    - graphviz
python:
  - "3.6"
  - "3.7"
env:
  matrix:
  - DJANGO=111
  - DJANGO=20
  - DJANGO=21
  - DJANGO=master
  - TOXENV=qa
  - TOXENV=docs
matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO=master
  exclude:
    - python: "3.7"
      env: TOXENV=docs
    - python: "3.7"
      env: DJANGO=111
    - python: "3.6"
      env: TOXENV=qa
install:
- pip install --upgrade pip tox
- pip install -U codecov
before_script:
- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
- nvm install --lts
- npm install -g standard
- |
  if [[ -z $TOXENV ]]; then
    export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
- echo $TOXENV
script:
- standard
- tox -e $TOXENV
after_success:
- codecov
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: fEP9K7y0ZF9fRvQEUN4kgPXQEZvi3Cx3ikUebG2UM/2uhcaUQm0+KpgZ2S+lvOTYcBnNgzPzFsVIZMcVcTxwIKuQDEMq9y2eop2hnisb9KXsIm9qPYSzOnRm74VuiOt4hNOZMe0qVBK2cO3vC9NDXuzdI8A0JynJhthfl4t+kFM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: applegrew/django-select2
